---
apiVersion: v1
kind: Pod
metadata:
  name: conjur-cli
  labels:
    app: web
spec:
  containers:
  - name: conjur-cli
    image: conjur-cli:local
    volumeMounts:
    - mountPath: /host-dir
      name: host-dir
  volumes:
  - name: host-dir
    hostPath:
      path: /Users/josephhunt/Conjur/scalability-k8s
