---
apiVersion: v1
kind: Service
metadata:
  name: follower-service
  labels:
    app: follower-service
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 5432
    name: pg-repl1
  - port: 5433
    name: pg-repl2
  selector:
    app: conjur-follower
    cluster-id: dev
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: follower-service
  labels:
    app: follower-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: follower-service
    spec:
      containers:
      - name: conjur-follower
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp /shared/follower-seed.tar /tmp; evoke unpack seed /tmp/follower-seed.tar"]
#              command: ["/bin/sh", "-c", "evoke configure follower"]
        volumeMounts:
        - mountPath: /host-mount
          name: launch-dir
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: launch-dir
        hostPath:
          path: <path-to-root-from-here-on-your-machine>/scalability-k8s

# it seems like a bad idea to have a mount a host volume in every container,
# esp. in a multi-node environment. So the init container mounts the host volume
# and copies the seed file into a shared volume. Unpacking a seed file destroys
# the tarfile so every follower needs its own.
      initContainers:
      - name: init-followers
        image: cdemo/curl:local
        command: ["/bin/sh", "-c", "while [ ! -f /host-mount/follower-seed.tar ]; do sleep 5; done; cp /host-mount/follower-seed.tar /shared"]
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        - name: launch-dir
          mountPath: /host-mount
