---
apiVersion: v1
kind: Pod
metadata:
  name: conjur-client
  labels:
    app: web
spec:
  containers:
  - name: conjur-client
    image: conjur-cli:local
    volumeMounts:
    - mountPath: /demo
      name: local-demo
  volumes:
  - name: local-demo
    hostPath:
      path: /Users/josephhunt/Conjur/conjur-k8s/demo
