---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: conjur-jade
  labels:
    app: conjur-jade
spec:
  serviceName: conjur-jade
  replicas: 1
  template:
    metadata:
      labels:
        app: unset		# used by conjur-service selector
        cluster-id: dev
    spec:
      containers:
      - name: conjur-jade
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-repl1
        - containerPort: 5433
