---
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldap
  selector:
    app: conjur-follower
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur-follower
    spec:
      containers:
      - name: conjur-appliance
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
