---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: conjur-quartz
  labels:
    app: conjur-quartz
spec:
  serviceName: conjur-quartz
  replicas: 1
  template:
    metadata:
      labels:
        app: unset	# used to designate master/standby roles
    spec:
      containers:
      - name: conjur-quartz
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: main
        - containerPort: 5433
          name: audit

