---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: conjur-onyx
  labels:
    app: conjur-onyx
spec:
  serviceName: conjur-onyx
  replicas: 1
  template:
    metadata:
      labels:
        app: unset	# used by conjur-service selector to point to master
    spec:
      containers:
      - name: conjur-onyx
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: main
        - containerPort: 5433
          name: audit
