---
apiVersion: v1
kind: Service
metadata:
  name: conjur-master
  labels:
    app: conjur-master
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  - port: 5432
    name: main
  - port: 5433
    name: audit
  selector:
    app: conjur-master		# initial conjur-master is conjur-master-set-0-0
  externalIPs: 
    - 192.168.99.100		# the IP address of the minikube vbox
