---
apiVersion: v1
kind: Service
metadata:
  name: conjur-master
  labels:
    app: conjur-master
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  - port: 5432
    name: main
  - port: 5433
    name: audit
  selector:
    app: conjur-master
  externalIPs: 
    - 192.168.99.100 # you can get this value w/ "minikube ip" command
