---
apiVersion: v1
kind: Service
metadata:
  name: conjur-service
  labels:
    app: conjur-service
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  - port: 5432
    name: pg-follower
  - port: 5433
    name: pg-standby
  selector:
    app: conjur-master		# point to current conjur master via label
    cluster-id: dev
  externalIPs: 
    - 192.168.99.100		# you can get this value w/ "minikube ip" command
