---
apiVersion: v1
kind: Service
metadata:
  name: conjur-service
  labels:
    app: conjur-service
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  selector:
    app: conjur-master		# initial conjur-master is conjur-master-set-0-0
    cluster-id: dev
  externalIPs: 
    - 192.168.99.100		# the IP address of the minikube vbox
