---
apiVersion: v1
kind: Service
metadata:
  name: conjur-follower
  labels:
    app: conjur-follower
spec:
  ports:
  - port: 443
    name: https
  - port: 636
    name: ldaps
  selector:
    app: conjur-follower
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conjur-follower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur-follower
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: launch-dir
        hostPath:
          path: {{seedfile-dir}}
      containers:
      - name: conjur-follower
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 5432
          name: pg-main
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp /shared/follower-seed.tar /tmp; evoke unpack seed /tmp/follower-seed.tar; evoke configure follower -j /etc/conjur.json"]
          
# it would seem a bad idea to mount a host volume in every container,
# esp. in a multi-node environment. So only the init container 
# mounts the host volume and copies the seed file into a shared volume. 
# Unpacking a seed file destroys the tarfile so every follower needs 
# its own. So the postStart hook above copies the seed file into the 
# container from the shared volume and unpacks it.
      initContainers:
      - name: init-followers
        image: conjur-cli:local
        command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
#        command: ["/bin/sh", "-c", "cp /host-dir/follower-seed.tar /shared" ]
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        - name: launch-dir
          mountPath: /host-dir
