---
apiVersion: v1
kind: Service
metadata:
  name: conjur-master-headless
spec:
  ports:
  - port: 443
  clusterIP: None
  selector:
    app: conjur-master
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: conjur-master
spec:
  serviceName: conjur-master
  replicas: 1
  template:
    metadata:
      labels:
        app: conjur-master
    spec:
      containers:
      - name: conjur-master
        image: conjur-appliance:local
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
        env:
        - name: MASTER_POD_NAME
          valueFrom:
            configMapKeyRef:
              name: conjur-master-config
              key: master-pod-name
        - name: CONJUR_MASTER_DNS_NAME
          valueFrom:
            configMapKeyRef:
              name: conjur-master-config
              key: conjur-master-dns-name
        - name: ROOT_KEY
          valueFrom:
            configMapKeyRef:
              name: conjur-master-config
              key: root-key
        - name: CONJUR_CLUSTER_ACCT
          valueFrom:
            configMapKeyRef:
              name: conjur-master-config
              key: conjur-cluster-acct
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "evoke configure master -h $CONJUR_MASTER_DNS_NAME -p $ROOT_KEY $CONJUR_CLUSTER_ACCT"]

