---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp1-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: launch-dir
        hostPath:
          path: {{demo-dir}}
      containers:
      - name: webapp1
        image: cdemo/curl:local
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        - name: launch-dir
          mountPath: /host-mount
        env:
        - name: ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: webapp1
              key: conjur_service_url
        - name: DEPLOYMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: webapp1
              key: deployment_name
        - name: VAR_ID
          valueFrom:
            configMapKeyRef:
              name: webapp1
              key: var_name
        - name: SLEEP_TIME
          valueFrom:
            configMapKeyRef:
              name: webapp1
              key: sleep_time
      initContainers:
      - name: init-democ
        image: conjur-cli:local
        command: ["/bin/sh", "-c", "cp /host-mount/api_key /shared/api_key"]
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        - name: launch-dir
          mountPath: /host-mount

