---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp1-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: cdemo/curl:local
        env:
          - name: ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: webapp1
                key: conjur-service-url
          - name: DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                name: webapp1
                key: deployment-name
          - name: API_KEY
            valueFrom:
              configMapKeyRef:
                name: webapp1
                key: api-key
          - name: VAR_ID
            valueFrom:
              configMapKeyRef:
                name: webapp1
                key: var-name
          - name: SLEEP_TIME
            valueFrom:
              configMapKeyRef:
                name: webapp1
                key: sleep-time
